version: '3.3'

services:
  buildbot:
    build:
      context: ../../
      dockerfile: docker/armhf-rust-buildenv/Dockerfile
    volumes:
      - type: bind
        source: ./target
        target: /streamium-server/target
